[project]
name = "psychopy-phidgets"
version = "0.0.1"
authors = [
  { name="Muhammad Qadri", email="mqadri@holycross.edu" },
]
description = "Psychopy plugin providing support for Phidgets"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GPLv3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/maqadri/psychopy-phidgets"
"Bug Tracker" = "https://github.com/maqadri/psychopy-phidgets/issues"